### ISSUE TITLE
Moodle Notification Issues

### ISSUE THREAD

**Issue by MXchuck** [mxschool/mxMoodle#61]
When the nurse hits the button to generate COVIDpass reminders, she gets an error.
SD-18068 in Jira

**Comment by MXchuck** [comment]
Coding error detected, it must be fixed by a programmer: Primary recipient has no valid option for salutation.
File: ...ol/classes/notification.php
Line: 101
Stack trace:
Error code: codingerror
* line 101 of /local/mxschool/classes/notification.php: coding_exception thrown
* line 54 of /local/mxschool/classes/bulk_notification.php: call to local_mxschool\notification->send()
* line ? of unknownfile: call to local_mxschool\bulk_notification->local_mxschool\{closure}()
* line 55 of /local/mxschool/classes/bulk_notification.php: call to array_reduce()
* line 156 of /local/mxschool/externallib.php: call to local_mxschool\bulk_notification->send()
* line 261 of /lib/externallib.php: call to local_mxschool_external::send_email()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by MXchuck** [comment]
In the preferences, the notification used {addresseelong} which I changed to {firstname} thinking that was the "salutation" issue.

**Comment by jrdegreeff** [comment]
I just saw this and thought I would jump in since I know exactly what the issue is. Not sure of the context, but whatever this notification is, it is violating a pre-condition that we built into the email sender that we must have some way to address the primary addressee (independent of what fields the email actually uses). See the specification here: https://github.com/mxschool/mxMoodle/blob/08fbb73297d6870a287d7d93f791b5afe1dc1295/local/mxschool/classes/notification.php#L93-L95

**Comment by MXchuck** [comment]
This does appear to be a missing data problem.
I've switched to firstname from the addressee meta tags.
